<?php 
$products = $this->getProducts(); 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
foreach ($products as $product){
  $_imagehelper = $objectManager->get('Magento\Catalog\Helper\Image');
  $image_url = $_imagehelper->init($product, 'cart_page_product_thumbnail')->getUrl();
  ?>
	<div class="order-item" style="margin-bottom:10px;">
	  <div class="item-img" style="display: inline-block; margin-right:10px;">
	  	<a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName() ?>"><img src="<?php echo $image_url ?>" alt="<?php echo $product->getName() ?>"></a>
	  </div>
	  <div class="item-detail" style="display:inline-block;">
	    <div class="product-name">
	    	<a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName() ?>"><?php echo $product->getName() ?></a>
	    </div>
	  </div>
	</div>
<?php } ?>
